/*
  # Create discussions table

  1. New Tables
    - `discussions`
      - `id` (integer, primary key)
      - `session_id` (varchar)
      - `type` (varchar)
      - `message` (text)
      - `created_at` (timestamp)
      - `client_name` (varchar)
      - `read` (boolean)
      - `assigned_to_agent` (boolean)

  2. Security
    - Enable RLS on discussions table
    - Add policies for authenticated users
*/

-- Drop existing policies if they exist
DO $$ 
BEGIN
  DROP POLICY IF EXISTS "Authenticated users can read all discussions" ON discussions;
  DROP POLICY IF EXISTS "Authenticated users can insert messages" ON discussions;
  DROP POLICY IF EXISTS "Authenticated users can update discussions" ON discussions;
  DROP POLICY IF EXISTS "Authenticated users can delete discussions" ON discussions;
EXCEPTION
  WHEN undefined_object THEN NULL;
END $$;

-- Create discussions table
CREATE TABLE IF NOT EXISTS discussions (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  session_id varchar NOT NULL,
  type varchar(10) CHECK (type IN ('human', 'ai')),
  message text NOT NULL,
  created_at timestamp without time zone DEFAULT now(),
  client_name varchar(255),
  read boolean DEFAULT false,
  assigned_to_agent boolean DEFAULT false
);

-- Enable RLS
ALTER TABLE discussions ENABLE ROW LEVEL SECURITY;

-- Create policies
CREATE POLICY "Authenticated users can read all discussions"
  ON discussions
  FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Authenticated users can insert messages"
  ON discussions
  FOR INSERT
  TO authenticated
  WITH CHECK (true);

CREATE POLICY "Authenticated users can update discussions"
  ON discussions
  FOR UPDATE
  TO authenticated
  USING (true);

CREATE POLICY "Authenticated users can delete discussions"
  ON discussions
  FOR DELETE
  TO authenticated
  USING (true);

-- Create indexes
CREATE INDEX IF NOT EXISTS discussions_session_id_idx ON discussions(session_id);
CREATE INDEX IF NOT EXISTS discussions_created_at_idx ON discussions(created_at);
CREATE INDEX IF NOT EXISTS discussions_read_idx ON discussions(read);
CREATE INDEX IF NOT EXISTS idx_discussions_assigned_to_agent ON discussions(assigned_to_agent);
CREATE INDEX IF NOT EXISTS idx_discussions_session_read ON discussions(session_id, read);