/*
  # Create discussions table

  1. New Tables
    - `discussions`
      - `id` (int4, primary key)
      - `session_id` (varchar)
      - `type` (varchar)
      - `message` (text)
      - `created_at` (timestamp)
      - `client_name` (varchar)
      - `read` (boolean)

  2. Security
    - Enable RLS on discussions table
    - Add policies for authenticated users
*/

-- Drop existing policies if they exist
DO $$ 
BEGIN
  DROP POLICY IF EXISTS "Authenticated users can read all discussions" ON discussions;
  DROP POLICY IF EXISTS "Authenticated users can create discussions" ON discussions;
  DROP POLICY IF EXISTS "Authenticated users can update discussions" ON discussions;
  DROP POLICY IF EXISTS "Authenticated users can delete discussions" ON discussions;
EXCEPTION
  WHEN undefined_object THEN NULL;
END $$;

-- Create discussions table if it doesn't exist
CREATE TABLE IF NOT EXISTS discussions (
  id int4 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  session_id varchar NOT NULL,
  type varchar NOT NULL CHECK (type IN ('human', 'ai')),
  message text NOT NULL,
  created_at timestamptz DEFAULT now(),
  client_name varchar NOT NULL,
  read boolean DEFAULT false
);

-- Enable RLS
ALTER TABLE discussions ENABLE ROW LEVEL SECURITY;

-- Create policies
CREATE POLICY "Authenticated users can read all discussions"
  ON discussions
  FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Authenticated users can create discussions"
  ON discussions
  FOR INSERT
  TO authenticated
  WITH CHECK (true);

CREATE POLICY "Authenticated users can update discussions"
  ON discussions
  FOR UPDATE
  TO authenticated
  USING (true);

CREATE POLICY "Authenticated users can delete discussions"
  ON discussions
  FOR DELETE
  TO authenticated
  USING (true);

-- Create indexes for faster lookups
DO $$ 
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_indexes 
    WHERE tablename = 'discussions' AND indexname = 'discussions_session_id_idx'
  ) THEN
    CREATE INDEX discussions_session_id_idx ON discussions(session_id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_indexes 
    WHERE tablename = 'discussions' AND indexname = 'discussions_created_at_idx'
  ) THEN
    CREATE INDEX discussions_created_at_idx ON discussions(created_at);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_indexes 
    WHERE tablename = 'discussions' AND indexname = 'discussions_read_idx'
  ) THEN
    CREATE INDEX discussions_read_idx ON discussions(read);
  END IF;
END $$;